import { ProfileBase } from './profile';

export const profileData: ProfileBase[] = [
    {
    units: "american",
    weight : 0,
    weightfinal : 0,
    heightfeet : 0,
    heightinches : 0,
    height : 0,
    abdomen : 0,
    abdomenfinal : 0,
    waist : 0,
    waistfinal : 0,
    neck : 0,
    neckfinal : 0,
    gender : 'male',
    
    mencirc : 0,
    menheight : 0,
    menfatper : 0,
    menfatmass : 0,
    menleanmass : 0,
    
    womencirc : 0,
    womenheight : 0,
    womenfatper : 0,
    womenfatmass : 0,
    womenleanmass : 0,

    finalfatper: 0,
    finalfatmass: 0,
    finalleanmass: 0,

    actmod: 1,
    goalmod: 1,
    goaltype: "",
    acttype: "",
    weightcal: 11.5,
    cardiocal: 6,
    weightmin: 0,
    cardiomin: 0,
    proteincal: 4,
    carbcal: 4,
    fatcal: 9,
    proteingram: 0,
    carbgram: 25,
    fatgram: 0,
    proteinratio: 0.69,
    proteinratiom: 1,
    proteinratiofinal: 0,

    bmr: 0,
    tef: 0,
    tdee: 0,
    weightcaltotal: 0,
    cardiocaltotal: 0,
    calgoalbase: 0,
    calgoalex: 0,

    proteincaltotal: 0,
    proteinper: 0,
    proteinperex: 0,

    carbcaltotal: 0,
    carbper: 0,
    carbperex: 0,

    fatcaltotal: 0,
    fatcalextotal: 0,
    fatgramex: 0,
    fatper: 0,
    fatperex: 0,

    proteinratiotemp: 0,
    tdeetemp: 0,
    proteinpertemp: 0,
    carbpertemp: 0,
    fatpertemp: 0,
    initialcalc: 0,
}
]